trigger:
- master

# FIXME: If you add more Python version to the matrix,
# do NOT calculate coverage for all of them; pick one.
pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -e ".[test]"
  displayName: 'Install dependencies'

- script: |
    python -m pip freeze
  displayName: 'Package listing'

- script: |
    python -m pip install pytest pytest-azurepipelines
    python get_waf.py
    python waf configure build
    pytest -rsv --cov=./ --cov-report=xml
    codecov -t "$CODECOV"
  displayName: 'pytest'
  env:
    CODECOV: $(codecov)
